# Generated by Django 5.1.1 on 2024-12-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_enterable',
            field=models.BooleanField(default=False),
        ),
    ]
