# Generated by Django 5.1.1 on 2024-12-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_is_enterable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='game.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_enterable',
            field=models.BooleanField(default=True),
        ),
    ]
