# Generated by Django 5.1.1 on 2025-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_user_in_game_alter_game_is_enterable'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
