# Generated by Django 5.1.1 on 2025-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_game_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='table',
            field=models.JSONField(default=list),
        ),
    ]
