# Generated by Django 5.1.1 on 2025-01-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
