# Generated by Django 5.1.1 on 2025-01-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='combination',
            field=models.JSONField(default=list),
        ),
    ]
