# Generated by Django 5.1.1 on 2025-01-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_game_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draw',
            field=models.BooleanField(default=False),
        ),
    ]
